services:
  TestWithDocker:
    image: testwithdocker1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5082:8080"  # Пробрасываем порт 80 контейнера на порт 8080 хоста
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
